# Generated by Django 5.1.7 on 2025-04-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_doctor_role_patient_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='role',
        ),
    ]
