# Generated by Django 5.1.7 on 2025-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_doctor_role_remove_patient_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/doctor_pictures'),
        ),
    ]
